version: '3'
networks:
  frontend:
  backend:

services:
  mysql:
    image: jfuwu/mysql
    volumes:
      - "./volumes/mysql:/apps/mysql"
    ports:
      - "3306:3306"
    environment:
      # 默认的root密码和需要新建的数据库、用户名、密码，若需要重新设置，需要删除volumes/mysql/下面的全部内容，然后重新build
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
      - MYSQL_USER=jfuwu
      - MYSQL_PASSWORD=jfuwu
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - backend

  redis:
    image: redis-3.0
    ports:
      - "6379:6379"
    networks:
      - backend
 
  # php7配置
  php71:
    image: jfuwu/php71
    volumes:
      - "./volumes/apps:/apps"
    networks:
      - backend
      - frontend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  nginx:
    image: jfuwu/nginx
    volumes:
      - "./volumes/apps:/apps"
      - "./nginx/config/conf.d:/etc/nginx/conf.d"
    ports:
      - "80:80"
      - "443:443"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - frontend